create table public.products (
  id bigint primary key check (id > 0),
  name text not null check (length(name) between 1 and 100),
  price_yen integer not null check (price_yen between 0 and 1000000),
  stock_quantity integer not null check (stock_quantity >= 0),
  is_active boolean not null default true
);

create table public.orders (
  id bigint generated by default as identity primary key,
  status text not null default 'pending'
    check (status in ('pending', 'validated', 'cancelled')),
  total_amount_yen integer not null check (total_amount_yen >= 0),
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity between 1 and 99),
  unit_price_yen integer not null check (unit_price_yen between 0 and 1000000)
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "active products are locally readable"
on public.products
for select
to anon, authenticated
using (is_active);

grant usage on schema public to anon, authenticated;
grant select on table public.products to anon, authenticated;

comment on table public.orders is
  'Schema lesson only: the bundled process-order function does not persist orders.';
